import localFont from "next/font/local";
import "./globals.css";
import CodeConverter from "./codeContext";
import { Toaster } from "react-hot-toast";
import Script from "next/script";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        <Script
          defer
          data-domain="code-converter-kohl.vercel.app"
          src="http://localhost:3000/tracking-script.js"
        />
      </head>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased bg-gray-100`}
      >
        <CodeConverter>{children}</CodeConverter>
        <Toaster />
      </body>
    </html>
  );
}
